"""
auth_window.py — Viper 鉴权锁定界面 (View A)
API Key 配置向导，验证通过后销毁自身并由 app.py 加载主窗口。
"""

from __future__ import annotations

import os
import sys
from pathlib import Path
from typing import Callable

import customtkinter as ctk

from config.settings import Settings
from utils.logger import get_logger

logger = get_logger(__name__)

# ── 主题常量 ─────────────────────────────────────────────────────────────────
BG        = "#0B0B0B"
BG2       = "#141414"
ACCENT    = "#B026FF"
ACCENT_DIM= "#7A18AD"
TEXT      = "#E0E0E0"
TEXT_DIM  = "#666666"
BORDER    = "#2A2A2A"


# ── 提供商配置 ────────────────────────────────────────────────────────────────
PROVIDERS: dict[str, dict] = {
    "Google Gemini (Recommended)": {
        "key":       "google",
        "env_key":   "GOOGLE_API_KEY",
        "models":    ["gemini-2.5-pro", "gemini-2.5-flash", "gemini-2.0-flash-exp", "gemini-2.0-flash"],
        "default":   "gemini-2.5-flash",
        "key_hint":  "AIza...",
        "api_url":   "https://aistudio.google.com/apikey",
        "vision":    True,
    },
    "OpenAI GPT / o-series": {
        "key":       "openai",
        "env_key":   "OPENAI_API_KEY",
        "models":    ["gpt-4.1", "gpt-4.1-mini", "gpt-4o", "o3", "o4-mini"],
        "default":   "gpt-4.1",
        "key_hint":  "sk-...",
        "api_url":   "https://platform.openai.com/api-keys",
        "vision":    True,
    },
    "Anthropic Claude": {
        "key":       "anthropic",
        "env_key":   "ANTHROPIC_API_KEY",
        "models":    ["claude-opus-4-5", "claude-sonnet-4-5", "claude-3-7-sonnet-20250219"],
        "default":   "claude-sonnet-4-5",
        "key_hint":  "sk-ant-...",
        "api_url":   "https://console.anthropic.com/settings/keys",
        "vision":    True,
    },
    "DeepSeek": {
        "key":       "deepseek",
        "env_key":   "DEEPSEEK_API_KEY",
        "models":    ["deepseek-chat", "deepseek-reasoner"],
        "default":   "deepseek-chat",
        "key_hint":  "sk-...",
        "api_url":   "https://platform.deepseek.com/api_keys",
        "vision":    False,
    },
    "Qwen (Aliyun DashScope)": {
        "key":       "qwen",
        "env_key":   "DASHSCOPE_API_KEY",
        "models":    ["qwen-max", "qwen-plus", "qwen-turbo", "qwen3-235b-a22b"],
        "default":   "qwen-max",
        "key_hint":  "sk-...",
        "api_url":   "https://dashscope.console.aliyun.com/apiKey",
        "vision":    False,
    },
    "Kimi (Moonshot)": {
        "key":       "moonshot",
        "env_key":   "MOONSHOT_API_KEY",
        "models":    ["moonshot-v1-128k", "kimi-latest", "moonshot-v1-32k"],
        "default":   "moonshot-v1-128k",
        "key_hint":  "sk-...",
        "api_url":   "https://platform.moonshot.cn/console/api-keys",
        "vision":    False,
    },
    "GLM (Zhipu AI)": {
        "key":       "zhipu",
        "env_key":   "ZHIPU_API_KEY",
        "models":    ["glm-4-plus", "glm-4-flash", "glm-4v-plus", "glm-z1-plus"],
        "default":   "glm-4-plus",
        "key_hint":  "eyJ...",
        "api_url":   "https://open.bigmodel.cn/usercenter/apikeys",
        "vision":    True,
    },
}


def _get_env_path() -> Path:
    ud = os.environ.get("VIPER_USER_DATA", "")
    if ud:
        return Path(ud) / ".env"
    return Path(__file__).resolve().parent.parent / ".env"


def _save_settings(provider_key: str, env_key: str, api_key: str, model: str) -> None:
    """将 API key 和模型写入 .env 文件，并同步到 Settings。"""
    env_path = _get_env_path()
    env_path.parent.mkdir(parents=True, exist_ok=True)

    existing: dict[str, str] = {}
    if env_path.exists():
        for line in env_path.read_text(encoding="utf-8").splitlines():
            if "=" in line and not line.strip().startswith("#"):
                k, _, v = line.partition("=")
                existing[k.strip()] = v.strip()

    existing[env_key]         = api_key
    existing["DEFAULT_MODEL"] = model
    existing["LLM_PROVIDER"]  = provider_key

    lines = ["# VIPER — auto-generated by auth window", ""]
    for k, v in existing.items():
        lines.append(f"{k}={v}")
    env_path.write_text("\n".join(lines), encoding="utf-8")

    # 运行时同步
    setattr(Settings, env_key, api_key)
    Settings.DEFAULT_MODEL = model
    Settings.LLM_PROVIDER  = provider_key
    logger.info(f"Settings saved: provider={provider_key}, model={model}")


class AuthWindow(ctk.CTk):
    """
    鉴权锁定主窗口 (View A)。
    验证成功后调用 on_auth_success() 回调，由 app.py 销毁并打开主窗口。
    """

    def __init__(self, on_auth_success: Callable[[], None]) -> None:
        super().__init__()
        self._on_auth_success = on_auth_success
        self._setup_window()
        self._build_ui()

    # ── 窗口基础设置 ──────────────────────────────────────────────────────────
    def _setup_window(self) -> None:
        self.title("VIPER — Bioinformatics Audit Agent")
        self.geometry("700x640")
        self.minsize(640, 580)
        self.resizable(True, True)
        self.configure(fg_color=BG)

        # 居中显示
        self.update_idletasks()
        sw = self.winfo_screenwidth()
        sh = self.winfo_screenheight()
        x = (sw - 700) // 2
        y = (sh - 640) // 2
        self.geometry(f"700x640+{x}+{y}")

        # 尝试设置图标 (兼容 PyInstaller --onefile)
        _base = Path(sys._MEIPASS) if getattr(sys, "frozen", False) else Path(__file__).parent.parent  # type: ignore[attr-defined]
        icon_path = _base / "assets" / "viper_icon.ico"
        if icon_path.exists():
            try:
                self.iconbitmap(str(icon_path))
            except Exception:
                pass

    # ── UI 构建 ──────────────────────────────────────────────────────────────
    def _build_ui(self) -> None:
        self.grid_columnconfigure(0, weight=1)
        self.grid_rowconfigure(0, weight=1)

        # 外层卡片
        card = ctk.CTkFrame(self, fg_color=BG2, corner_radius=16,
                            border_width=1, border_color=BORDER)
        card.grid(row=0, column=0, padx=60, pady=40, sticky="nsew")
        card.grid_columnconfigure(0, weight=1)

        # ── Logo 头部 ────────────────────────────────────────────────────────
        logo_frame = ctk.CTkFrame(card, fg_color="transparent")
        logo_frame.grid(row=0, column=0, pady=(36, 8))

        ctk.CTkLabel(
            logo_frame, text="🐍",
            font=ctk.CTkFont(size=52),
        ).pack()
        ctk.CTkLabel(
            logo_frame, text="VIPER",
            font=ctk.CTkFont(family="Consolas", size=32, weight="bold"),
            text_color=ACCENT,
        ).pack()
        ctk.CTkLabel(
            logo_frame, text="BIOINFORMATICS  AUDIT  AGENT",
            font=ctk.CTkFont(family="Consolas", size=10),
            text_color=TEXT_DIM,
        ).pack(pady=(2, 0))

        # ── 分隔线 ───────────────────────────────────────────────────────────
        sep = ctk.CTkFrame(card, height=1, fg_color=BORDER)
        sep.grid(row=1, column=0, sticky="ew", padx=30, pady=(12, 20))

        # ── 表单区 ───────────────────────────────────────────────────────────
        form = ctk.CTkFrame(card, fg_color="transparent")
        form.grid(row=2, column=0, sticky="ew", padx=40)
        form.grid_columnconfigure(0, weight=1)

        # Provider
        ctk.CTkLabel(form, text="LLM Provider",
                     font=ctk.CTkFont(size=12, weight="bold"),
                     text_color=TEXT).grid(row=0, column=0, sticky="w", pady=(0, 4))

        self._provider_var = ctk.StringVar(value=list(PROVIDERS.keys())[0])
        self._provider_menu = ctk.CTkOptionMenu(
            form,
            variable=self._provider_var,
            values=list(PROVIDERS.keys()),
            fg_color=BG, button_color=ACCENT, button_hover_color=ACCENT_DIM,
            dropdown_fg_color=BG2, dropdown_hover_color=BORDER,
            text_color=TEXT, dropdown_text_color=TEXT,
            font=ctk.CTkFont(size=13),
            command=self._on_provider_change,
            height=38,
            corner_radius=8,
        )
        self._provider_menu.grid(row=1, column=0, sticky="ew", pady=(0, 14))

        # Model
        ctk.CTkLabel(form, text="Model",
                     font=ctk.CTkFont(size=12, weight="bold"),
                     text_color=TEXT).grid(row=2, column=0, sticky="w", pady=(0, 4))

        self._model_var = ctk.StringVar()
        self._model_entry = ctk.CTkEntry(
            form,
            textvariable=self._model_var,
            placeholder_text="e.g. gemini-2.5-pro  (any model ID)",
            fg_color=BG, border_color=BORDER, text_color=TEXT,
            placeholder_text_color=TEXT_DIM,
            height=38, corner_radius=8,
            font=ctk.CTkFont(family="Consolas", size=13),
        )
        self._model_entry.grid(row=3, column=0, sticky="ew", pady=(0, 4))

        # 快捷模型列表
        self._model_quick_frame = ctk.CTkFrame(form, fg_color="transparent")
        self._model_quick_frame.grid(row=4, column=0, sticky="ew", pady=(0, 14))

        # API Key
        self._key_label = ctk.CTkLabel(
            form, text="API Key",
            font=ctk.CTkFont(size=12, weight="bold"),
            text_color=TEXT
        )
        self._key_label.grid(row=5, column=0, sticky="w", pady=(0, 4))

        self._key_entry = ctk.CTkEntry(
            form,
            placeholder_text="Paste your API key here",
            fg_color=BG, border_color=BORDER, text_color=TEXT,
            placeholder_text_color=TEXT_DIM,
            height=42, corner_radius=8,
            font=ctk.CTkFont(family="Consolas", size=13),
            show="●",
        )
        self._key_entry.grid(row=6, column=0, sticky="ew", pady=(0, 6))

        # 密码可见切换
        self._show_key = False
        ctk.CTkButton(
            form, text="Show / Hide", width=100, height=26,
            fg_color="transparent", hover_color=BORDER,
            text_color=TEXT_DIM, font=ctk.CTkFont(size=11),
            command=self._toggle_key_visibility,
        ).grid(row=7, column=0, sticky="e", pady=(0, 16))

        # 错误提示标签
        self._error_label = ctk.CTkLabel(
            form, text="",
            text_color="#FF4444",
            font=ctk.CTkFont(size=12),
            wraplength=400,
        )
        self._error_label.grid(row=8, column=0, pady=(0, 8))

        # Connect 按钮
        self._connect_btn = ctk.CTkButton(
            form,
            text="⚡  Connect & Launch Viper",
            font=ctk.CTkFont(family="Consolas", size=14, weight="bold"),
            fg_color=ACCENT, hover_color=ACCENT_DIM,
            text_color="white",
            height=46, corner_radius=10,
            command=self._on_connect,
        )
        self._connect_btn.grid(row=9, column=0, sticky="ew", pady=(0, 10))

        # 底部版权
        ctk.CTkLabel(
            card, text="Viper  ·  Local Desktop Agent  ·  Keys stored in .env",
            font=ctk.CTkFont(size=10),
            text_color=TEXT_DIM,
        ).grid(row=3, column=0, pady=(8, 20))

        # 初始化 provider
        self._on_provider_change(list(PROVIDERS.keys())[0])

    # ── 交互逻辑 ─────────────────────────────────────────────────────────────
    def _on_provider_change(self, choice: str) -> None:
        cfg = PROVIDERS[choice]
        # 更新快捷模型按钮
        for w in self._model_quick_frame.winfo_children():
            w.destroy()
        for m in cfg["models"][:4]:
            btn = ctk.CTkButton(
                self._model_quick_frame, text=m,
                width=0, height=24,
                fg_color=BORDER, hover_color="#3A3A3A",
                text_color=TEXT_DIM, font=ctk.CTkFont(family="Consolas", size=11),
                corner_radius=4,
                command=lambda name=m: self._model_var.set(name),
            )
            btn.pack(side="left", padx=(0, 6))
        self._model_var.set(cfg["default"])
        self._key_label.configure(text=f"API Key  ({cfg['env_key']})")
        self._key_entry.configure(placeholder_text=cfg["key_hint"])

    def _toggle_key_visibility(self) -> None:
        self._show_key = not self._show_key
        self._key_entry.configure(show="" if self._show_key else "●")

    def _on_connect(self) -> None:
        provider_label = self._provider_var.get()
        cfg = PROVIDERS[provider_label]
        api_key = self._key_entry.get().strip()
        model = self._model_var.get().strip()

        # 校验
        if len(api_key) < 8:
            self._error_label.configure(text="⚠  API key is too short — please check and retry.")
            return
        if not model:
            self._error_label.configure(text="⚠  Please enter or select a model name.")
            return

        self._error_label.configure(text="")
        self._connect_btn.configure(state="disabled", text="Connecting...")

        try:
            _save_settings(cfg["key"], cfg["env_key"], api_key, model)
            self.after(200, self._on_auth_success)
        except Exception as e:
            self._connect_btn.configure(state="normal", text="⚡  Connect & Launch Viper")
            self._error_label.configure(text=f"⚠  Error: {e}")
